### ISSUE TITLE
Scan ID raises an error when video capture device is closed or canceled

### ISSUE THREAD

**Issue by jedymatt** [comskie/prjApokonMonitoringSystem#4]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/54795428/187079161-148f289a-dade-4fc6-a271-901eea63367f.png">
<img width="912" alt="image" src="https://user-images.githubusercontent.com/54795428/187079176-230647e4-bd7f-4b5f-a360-52d4e3cf4e21.png">

**Comment by vinxentience** [comment]
oh nooo! thank you for noticing this. Maybe you could fix it for me? uwwwwu~~ 👉👈

**Comment by jedymatt** [comment]
@vinxentience please confirm if it also raises an error on your end.
